apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-v1
  namespace: default
  labels:
    app: test-app
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: applicaiton
          image: {{.Values.image}}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: endpoint
                  optional: false

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
                  optional: false

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
                  optional: false
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
